import type { StorybookCheckContext } from './context';
import { assertNoDecorativeEffects, assertNoOverRoundedUsage } from '../style-contract';

export function checkStoriesContracts(context: StorybookCheckContext): void {
  const { failures, buttonsComponent, buttonPlayground, dataDisplayComponent, feedbackComponent, formsComponent, interactionComponent, interactionProbe, layoutComponent, themeLocaleStressComponent, button } = context;

  for (const requiredText of [
    '../src/lib/components/Button.svelte',
    '../src/lib/components/ConfirmAction.svelte',
    '../src/lib/components/Icon.svelte',
    '../src/lib/components/IconButton.svelte',
    '../src/lib/components/Inline.svelte',
    '../src/lib/components/Stack.svelte',
    '../src/lib/components/Surface.svelte',
    '../src/lib/components/VisuallyHidden.svelte',
    'Button states',
    'data-zdp-theme="light"',
    'data-zdp-theme="dark"',
    'line-height: var(--zdp-type-title-line-height)',
    '기본 작업',
    '비활성 작업',
    '저장',
    'onclick={() => (lightActionCount += 1)}',
    'onclick={() => (darkActionCount += 1)}',
    'ariaControls="buttons-light-status"',
    'ariaControls="buttons-dark-status"',
    'ariaExpanded={lightActionCount > 0}',
    'ariaExpanded={darkActionCount > 0}',
    'ariaDescribedBy="buttons-light-status"',
    'ariaDescribedBy="buttons-dark-status"',
    'ariaPressed={lightIconPressed}',
    'ariaPressed={darkIconPressed}',
    'onclick={() => (lightIconPressed = !lightIconPressed)}',
    'onclick={() => (darkIconPressed = !darkIconPressed)}',
    '밀어서 결제하기',
    '밀어서 삭제하기',
    '또는 2초간 누르기',
    'onconfirm={() => (lightConfirmCount += 1)}',
    'onconfirm={() => (darkConfirmCount += 1)}',
    'id="buttons-light-status"',
    'id="buttons-dark-status"',
    'story-status',
    '새 항목 ',
    '<Icon size="sm">+</Icon>',
    '추가',
    '삭제',
    'ariaLabel="추가"',
    'disabled',
    'zdp-surface-reset'
  ]) {
    if (!buttonsComponent.includes(requiredText)) {
      failures.push(`Buttons story surface is missing ${requiredText}.`);
    }
  }

  const secondaryButtonBlock = button.slice(
    button.indexOf('.zdp-button--secondary {'),
    button.indexOf('.zdp-button--secondary:hover')
  );

  const dangerButtonBlock = button.slice(
    button.indexOf('.zdp-button--danger {'),
    button.indexOf('.zdp-button--danger:hover')
  );

  const dangerButtonHoverBlock = button.slice(
    button.indexOf('.zdp-button--danger:hover:not(:disabled)'),
    button.indexOf('.zdp-button--danger:active:not(:disabled)')
  );

  if (!secondaryButtonBlock.includes('background: var(--zdp-color-surface-raised)')) {
    failures.push('Button secondary variant must keep a visible tonal surface without relying on a border.');
  }

  for (const requiredText of ['background: var(--zdp-color-accent-danger)', 'color: var(--zdp-color-ink-inverse)']) {
    if (!dangerButtonBlock.includes(requiredText)) {
      failures.push(`Button danger variant must keep a contrast-safe filled surface: ${requiredText}.`);
    }
  }

  for (const requiredText of ['background: var(--zdp-color-surface-panel)', 'color: var(--zdp-color-accent-danger)']) {
    if (!dangerButtonHoverBlock.includes(requiredText)) {
      failures.push(`Button danger hover must keep its label visible: ${requiredText}.`);
    }
  }

  for (const requiredText of [
    '../src/lib/components/Badge.svelte',
    '../src/lib/components/Button.svelte',
    '../src/lib/components/Callout.svelte',
    '../src/lib/components/CodeBlock.svelte',
    '../src/lib/components/CommandField.svelte',
    '../src/lib/components/InlineCode.svelte',
    '../src/lib/components/Pagination.svelte',
    '../src/lib/components/Progress.svelte',
    '../src/lib/components/Skeleton.svelte',
    '../src/lib/components/SortHeader.svelte',
    '../src/lib/components/Spinner.svelte',
    '../src/lib/components/Table.svelte',
    '../src/lib/components/TableToolbar.svelte',
    '../src/lib/components/Toast.svelte',
    '../src/lib/components/Tooltip.svelte',
    'Theme / Locale Stress',
    '긴 문장과 초점 확인',
    "id: 'light'",
    "id: 'dark'",
    'data-zdp-theme={theme.id}',
    '24.375rem',
    "lang: 'ko'",
    "lang: 'en'",
    "lang: 'zh'",
    "lang: 'hi'",
    "lang: 'vi'",
    "lang: 'ru'",
    "lang: 'ms'",
    "lang: 'th'",
    '승인대기중인긴프로젝트이름',
    'Super-long audit trail names',
    '这是一个非常长的状态说明',
    'Un nombre de proyecto excepcionalmente largo',
    'Un message de vérification particulièrement long',
    'लंबे समीक्षा संदेश',
    '非常に長いプロジェクト名',
    'Chuỗi trạng thái rất dài',
    'Очень длинное сообщение',
    'Nama tugas dan pesan pemeriksaan yang sangat panjang',
    'Nama tugasan yang panjang',
    'ข้อความสถานะภาษาไทยที่ยาวมาก',
    '12 target locales · active ko/en',
    'stress-force-focus',
    'stress-device',
    'stress-locale-card',
    'stress-focus-grid',
    'outline: var(--zdp-control-focus-outline-width) solid var(--zdp-color-focus-surface)',
    'border-color: var(--zdp-color-focus-line)',
    '.stress-force-focus :global(.zdp-button)',
    '.stress-force-focus :global(.zdp-command-field)',
    '.stress-force-focus :global(.zdp-pagination__link:not(:disabled))',
    'aria-sort={theme.id ===',
    '<SortHeader',
    '<TableToolbar',
    '<Pagination',
    '<CommandField',
    '<Tooltip',
    '<Toast',
    '<Skeleton variant="text" lines={3} />',
    '<CodeBlock',
    'horizontalOverflowProbe',
    'overflow-wrap: var(--zdp-i18n-overflow-wrap)',
    'Tab으로 이동했을 때 테두리와 outline이 잘리지 않아야 합니다.',
    'A long status toast should stay readable without pretending to own queue timing.'
  ]) {
    if (!themeLocaleStressComponent.includes(requiredText)) {
      failures.push(`Theme locale stress story surface is missing ${requiredText}.`);
    }
  }

  for (const forbiddenText of [
    'code={codeExample}\n                  wrap',
    '.stress-panel :global(th)',
    '.stress-panel :global(td)'
  ]) {
    if (themeLocaleStressComponent.includes(forbiddenText)) {
      failures.push(`Theme locale stress story must not force fixed-format table/code content into wrapping: ${forbiddenText}.`);
    }
  }

  for (const requiredText of [
    '../src/lib/components/Button.svelte',
    '../src/lib/components/Icon.svelte',
    '../src/lib/components/Stack.svelte',
    '../src/lib/components/Surface.svelte',
    '../src/lib/components/VisuallyHidden.svelte',
    'export let variant',
    'export let size',
    'export let label',
    'export let disabled',
    'export let showIcon',
    'export let ariaKeyShortcuts',
    'Button playground',
    'Controls에서 라벨, 크기, 상태를 바꿔',
    'ariaDescribedBy="button-playground-status"',
    'onclick={() => (clickCount += 1)}',
    'button-playground__control',
    'button-playground__status',
    'zdp-surface-reset'
  ]) {
    if (!buttonPlayground.includes(requiredText)) {
      failures.push(`Button controls story surface is missing ${requiredText}.`);
    }
  }

  for (const requiredText of [
    '../src/lib/components/Button.svelte',
    '../src/lib/components/ConfirmAction.svelte',
    '../src/lib/components/Dialog.svelte',
    '../src/lib/components/CommandField.svelte',
    '../src/lib/components/Menu.svelte',
    '../src/lib/components/Popover.svelte',
    '../src/lib/components/Tabs.svelte',
    '../src/lib/menu.ts',
    'Interaction probe',
    'comboboxOptions',
    'filteredComboboxOptions',
    'commandQuery',
    'commandKeyState',
    'interaction-probe-command',
    'interaction-probe-command-help',
    'interaction-probe-command-results',
    'ariaKeyShortcuts="/"',
    'ariaAutocomplete="list"',
    'ariaActivedescendant={commandQuery ?',
    'onkeydown={(event) =>',
    'interaction-probe-combobox',
    'interaction-probe-combobox-state',
    'onQueryChange={(nextQuery) => (comboboxQuery = nextQuery)}',
    'onValueChange={(nextValue, option) =>',
    'ariaLabel="검토 섹션"',
    "selectedId = 'overview'",
    '기록이 선택되었습니다.',
    'ariaControls="interaction-probe-dialog"',
    'ariaExpanded={dialogOpen}',
    'onClose={() => (dialogOpen = false)}',
    'menuSelection',
    'interaction-probe-menu',
    'interaction-probe-menu-state',
    'onSelect={(_, item) => (menuSelection = item.label)}',
    '필터 저장',
    'popoverState',
    'interaction-probe-popover-title',
    'interaction-probe-popover',
    'interaction-probe-popover-state',
    'onOpenChange={(open) => (popoverState = open ?',
    '필터 열기',
    'Popover {popoverState}',
    '바깥 액션',
    'durationMs={600}',
    'onconfirm={() => (confirmCount += 1)}',
    '확인 {confirmCount}회',
    'zdp-surface-reset'
  ]) {
    if (!interactionProbe.includes(requiredText)) {
      failures.push(`Interaction probe story surface is missing ${requiredText}.`);
    }
  }

  for (const requiredText of [
    '../src/lib/components/Badge.svelte',
    '../src/lib/components/Avatar.svelte',
    '../src/lib/components/Button.svelte',
    '../src/lib/components/CodeBlock.svelte',
    '../src/lib/components/EmptyState.svelte',
    '../src/lib/components/IdentityChip.svelte',
    '../src/lib/components/Inline.svelte',
    '../src/lib/components/InlineCode.svelte',
    '../src/lib/components/KeyValue.svelte',
    '../src/lib/components/Stack.svelte',
    '../src/lib/components/SortHeader.svelte',
    '../src/lib/components/Surface.svelte',
    '../src/lib/components/Table.svelte',
    '../src/lib/components/TableToolbar.svelte',
    'Operational information',
    'data-zdp-theme="light"',
    'data-zdp-theme="dark"',
    '보안 점검',
    '보안 점검 목록',
    '담당자',
    '홍길동',
    '김하늘',
    '검토 담당',
    '운영 담당',
    '문서 조각',
    '승격 조건',
    '보안 기준',
    '<InlineCode text="readonly" />',
    '<InlineCode text="server-only" />',
    '<CodeBlock',
    'code={lightCodeExample}',
    'code={darkCodeExample}',
    '<TableToolbar',
    'selectedCount={2}',
    'aria-sort="ascending"',
    'aria-sort="descending"',
    '<SortHeader label="항목" direction="ascending" />',
    '<SortHeader label="상태" direction="descending" />',
    '<th scope="row">권한 분리</th>',
    '<KeyValue columns="two"',
    '원장 경계',
    'zdp-money-platform',
    'zdp-products-lab',
    '아직 공개할 변경이 없습니다.',
    '대기 중인 알림이 없습니다.',
    'slot="actions"',
    'zdp-surface-reset'
  ]) {
    if (!dataDisplayComponent.includes(requiredText)) {
      failures.push(`Data display story surface is missing ${requiredText}.`);
    }
  }

  for (const requiredText of [
    '../src/lib/components/Badge.svelte',
    '../src/lib/components/Callout.svelte',
    '../src/lib/components/Divider.svelte',
    '../src/lib/components/Inline.svelte',
    '../src/lib/components/Progress.svelte',
    '../src/lib/components/Skeleton.svelte',
    '../src/lib/components/Stack.svelte',
    '../src/lib/components/StatusToast.svelte',
    '../src/lib/components/Spinner.svelte',
    '../src/lib/components/Surface.svelte',
    '../src/lib/components/Toast.svelte',
    '../src/lib/toast.ts',
    'Status and surfaces',
    'data-zdp-theme="light"',
    'data-zdp-theme="dark"',
    'line-height: var(--zdp-type-title-line-height)',
    '검토 중',
    '정상',
    '대기',
    '주의',
    '다음 단계가 준비됐습니다.',
    '삭제 전에 다시 확인하세요.',
    '작업 흐름이 준비됐습니다.',
    '위험 작업 전에 다시 확인하세요.',
    '초안이 준비됐습니다.',
    '작업이 저장됐습니다.',
    '저장됐습니다.',
    '동기화가 끝났습니다.',
    '확인이 필요합니다.',
    '연결이 끊겼습니다.',
    'feedback-light-progress-title',
    'feedback-dark-progress-title',
    '자료를 불러오는 중입니다.',
    '목록 확인 중',
    '응답을 기다리고 있습니다.',
    '응답 대기 중',
    'variant="text"',
    'variant="block"',
    'variant="avatar"',
    'placement="inline"',
    'idPrefix="feedback-light-status-toast"',
    'idPrefix="feedback-dark-status-toast"',
    'onDismiss={(_, item) =>',
    '<Divider />',
    'surface-pair',
    'Parchment',
    'Banner',
    'zdp-surface-reset'
  ]) {
    if (!feedbackComponent.includes(requiredText)) {
      failures.push(`Feedback story surface is missing ${requiredText}.`);
    }
  }

  for (const requiredText of [
    '../src/lib/components/Checkbox.svelte',
    '../src/lib/components/Combobox.svelte',
    '../src/lib/components/ErrorText.svelte',
    '../src/lib/components/Field.svelte',
    '../src/lib/components/HelpText.svelte',
    '../src/lib/components/Input.svelte',
    '../src/lib/components/Label.svelte',
    '../src/lib/components/Radio.svelte',
    '../src/lib/components/Select.svelte',
    '../src/lib/components/Stack.svelte',
    '../src/lib/components/Surface.svelte',
    '../src/lib/components/Switch.svelte',
    '../src/lib/components/Textarea.svelte',
    'Control states',
    'data-zdp-theme="light"',
    'data-zdp-theme="dark"',
    'line-height: var(--zdp-type-title-line-height)',
    'forms-light-id',
    'forms-dark-id',
    'forms-light-email',
    'forms-dark-email',
    'forms-light-owner',
    'forms-dark-owner',
    '<Combobox',
    '담당 팀 찾기',
    '가장 가까운 담당 팀을 선택하세요.',
    'readonly',
    'disabled',
    '이미 발급된 값은 그대로 둡니다.',
    "describedBy={['forms-light-status-help', 'forms-light-status-error']}",
    "describedBy={['forms-dark-status-help', 'forms-dark-status-error']}",
    'errorMessageId="forms-light-status-error"',
    'errorMessageId="forms-dark-status-error"',
    '현재 작업 상태를 선택하세요.',
    '다음 단계 전에 기준을 확인하세요.',
    '초대 기능이 열리면 수정할 수 있습니다.',
    '업데이트 받기',
    '알림 주기',
    '자동 저장',
    'role="radiogroup"',
    'zdp-surface-reset'
  ]) {
    if (!formsComponent.includes(requiredText)) {
      failures.push(`Forms story surface is missing ${requiredText}.`);
    }
  }

  for (const requiredText of [
    '../src/lib/components/Button.svelte',
    '../src/lib/components/Card.svelte',
    '../src/lib/components/CardHeader.svelte',
    '../src/lib/components/Container.svelte',
    '../src/lib/components/Grid.svelte',
    '../src/lib/components/Inline.svelte',
    '../src/lib/components/Page.svelte',
    '../src/lib/components/PageHeader.svelte',
    '../src/lib/components/ResizableSplitPane.svelte',
    '../src/lib/components/Section.svelte',
    '../src/lib/components/Sheet.svelte',
    '../src/lib/components/Stack.svelte',
    '../src/lib/components/Toolbar.svelte',
    '화면의 첫 장면',
    '작업을 모으는 폭',
    '읽기 좋은 본문 폭',
    '검토 흐름 정리',
    '읽을 곳을 내 손에 맞추기',
    '<Page as="div" tone="canvas" labelledBy="layout-story-title">',
    '<Section spacing="xl">',
    '<Container size="lg" gutter="page">',
    '<PageHeader labelledBy="layout-story-title" align="center">',
    '<svelte:fragment slot="actions">',
    '<Grid columns="two" gap="md" labelledBy="layout-panel-title">',
    '<Card as="section" ariaLabelledBy="layout-public-card-title" hover>',
    '<CardHeader id="layout-public-card-title">공개 표면</CardHeader>',
    '<Toolbar labelledBy="layout-toolbar-title">',
    '<ResizableSplitPane',
    'bind:size={splitPaneSize}',
    'ariaLabel="목차 너비 조절"',
    'onResizeCommit={(size) => splitPanePersistence.save(size)}',
    '{#snippet primary()}',
    '목차 열기',
    'placement="left"',
    'zdp-surface-reset'
  ]) {
    if (!layoutComponent.includes(requiredText)) {
      failures.push(`Layout story surface is missing ${requiredText}.`);
    }
  }

  assertNoDecorativeEffects(failures, 'Layout story surface', layoutComponent);

  assertNoOverRoundedUsage(failures, 'Layout story surface', layoutComponent);

  for (const requiredText of [
    '../src/lib/components/Accordion.svelte',
    '../src/lib/components/Button.svelte',
    '../src/lib/components/Disclosure.svelte',
    '../src/lib/components/Dialog.svelte',
    '../src/lib/components/Divider.svelte',
    '../src/lib/components/Inline.svelte',
    '../src/lib/components/Kbd.svelte',
    '../src/lib/components/LocaleSwitcher.svelte',
    '../src/lib/components/CommandField.svelte',
    '../src/lib/components/Menu.svelte',
    '../src/lib/components/Popover.svelte',
    '../src/lib/components/SegmentedControl.svelte',
    '../src/lib/components/ShareDock.svelte',
    '../src/lib/components/ShortcutHint.svelte',
    '../src/lib/components/Stack.svelte',
    '../src/lib/components/Surface.svelte',
    '../src/lib/components/Tabs.svelte',
    '../src/lib/components/TermSheet.svelte',
    '../src/lib/components/TermTrigger.svelte',
    '../src/lib/components/TextScaleControl.svelte',
    '../src/lib/components/ThemeToggle.svelte',
    '../src/lib/components/Tooltip.svelte',
    '../src/lib/disclosure.ts',
    '../src/lib/menu.ts',
    '../src/lib/segmented.ts',
    '../src/lib/share.ts',
    '../src/lib/shortcuts.ts',
    '../src/lib/term.ts',
    '../src/lib/theme.ts',
    'Interaction states',
    'id="interaction-main"',
    'tabindex="-1"',
    'data-zdp-theme="light"',
    'data-zdp-theme="dark"',
    'line-height: var(--zdp-type-title-line-height)',
    'Tabs',
    'Command Field',
    'interaction-light-command',
    'interaction-dark-command',
    '프로젝트, 문서, 설정 검색',
    '검색어 없음',
    'Shortcut hints',
    'Locale Switcher',
    '<LocaleSwitcher',
    'lightLocale',
    'darkLocale',
    'localeOptions',
    'ariaLabel="Light locale"',
    'ariaLabel="Dark locale"',
    'Theme Toggle',
    '<ThemeToggle',
    'Text Scale Control',
    '<TextScaleControl',
    'lightTextScale',
    'darkTextScale',
    'ariaLabel="Light text scale"',
    'ariaLabel="Dark text scale"',
    'lightTheme',
    'darkTheme',
    "lightTheme === 'dark' ? 'light' : 'dark'",
    "darkTheme === 'dark' ? 'light' : 'dark'",
    'Tooltip',
    'Accordion and Disclosure',
    'Segmented Control',
    'Popover and Menu',
    'Term Sheet',
    'Kbd',
    'ShortcutHint',
    'zdpShortcutRecommendations',
    'zdpShortcutReservedExamples',
    'visibleShortcutRecommendations',
    'reservedShortcutPreview',
    'keydown 처리는 각 화면에 남깁니다',
    'Light shortcut hints',
    'Dark shortcut hints',
    'role="group" aria-label="Light shortcut hints"',
    'role="group" aria-label="Dark shortcut hints"',
    'Search',
    'Guide',
    'Open',
    'Previous',
    'Next',
    'Submit',
    'Close',
    'Typing',
    'IME',
    'Reserved',
    'shortcut-policy',
    'role="group" aria-label="Light shortcut guard examples"',
    'role="group" aria-label="Dark shortcut guard examples"',
    'Global shortcuts off while typing',
    'Global shortcuts off during IME composition',
    'text="새 항목"',
    'text="닫기"',
    'placement="right"',
    'let:describedBy',
    'ariaDescribedBy={describedBy}',
    'lightAccordionItems',
    'darkAccordionItems',
    'headingLevel={4}',
    'ariaLabel="Light disclosure sections"',
    'ariaLabel="Dark disclosure sections"',
    'lightSegmentedSelection',
    'darkSegmentedSelection',
    'lightTermOpen',
    'darkTermOpen',
    'lightSegmentedItems',
    'darkSegmentedItems',
    'termExample',
    'ZdpTermSheetTerm',
    'ariaLabel="Light view mode"',
    'ariaLabel="Dark view mode"',
    '보기 방식',
    '목록',
    '검토 기준',
    '접힌 안내',
    'idPrefix="interaction-light-popover"',
    'idPrefix="interaction-dark-popover"',
    'idPrefix="interaction-light-menu"',
    'idPrefix="interaction-dark-menu"',
    'triggerLabel="더보기"',
    'onSelect={(_, item) => (lightMenuSelection = item.label)}',
    'onSelect={(_, item) => (darkMenuSelection = item.label)}',
    '<TermTrigger',
    '<TermSheet',
    'controls="interaction-light-term-sheet"',
    'controls="interaction-dark-term-sheet"',
    'id="interaction-light-term-sheet"',
    'id="interaction-dark-term-sheet"',
    'onClose={() => (lightTermOpen = false)}',
    'onClose={() => (darkTermOpen = false)}',
    '운영 복원력',
    '용어 열림',
    '용어 닫힘',
    '설정 열기',
    '필터 저장',
    '연결 끊기',
    'Dialog',
    'Light interaction sections',
    'Dark interaction sections',
    'idPrefix="interaction-light-tabs"',
    'idPrefix="interaction-dark-tabs"',
    'selectedId="overview"',
    'let:selectedId',
    'disabled: true',
    '<Divider />',
    'lightDialogOpen',
    'darkDialogOpen',
    'ariaControls="interaction-light-dialog"',
    'ariaControls="interaction-dark-dialog"',
    'ariaExpanded={lightDialogOpen}',
    'ariaExpanded={darkDialogOpen}',
    'onClose={() => (lightDialogOpen = false)}',
    'onClose={() => (darkDialogOpen = false)}',
    '검토 열기',
    '변경 내용을 저장할까요?',
    '삭제 전에 확인하세요.',
    '<Button variant="primary" onclick={() => (lightDialogOpen = false)}>저장</Button>',
    '<Button variant="danger" onclick={() => (darkDialogOpen = false)}>삭제</Button>',
    '<ShareDock placement="inline"',
    'Light share actions',
    'Dark share actions',
    '링크 복사',
    '기기 공유',
    '텔레그램',
    '라인',
    '왓츠앱',
    '레딧',
    'zdp-surface-reset'
  ]) {
    if (!interactionComponent.includes(requiredText)) {
      failures.push(`Interaction story surface is missing ${requiredText}.`);
    }
  }
}
