import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { siLine, siReddit, siTelegram, siWhatsapp, siX } from 'simple-icons';
import { assertNoDecorativeEffects, assertNoOverRoundedUsage } from './style-contract';

const root = process.cwd();
const previewPath = join(root, 'preview', 'index.html');
const styleEntryPath = join(root, 'src', 'styles', 'index.css');
const tokenStylePath = join(root, 'src', 'styles', 'tokens.css');
const brandFontStylePath = join(root, 'src', 'styles', 'brand-fonts.css');
const expressiveFontStylePath = join(root, 'src', 'styles', 'expressive-fonts.css');
const localeFontStylePath = join(root, 'src', 'styles', 'locale-fonts.css');
const componentStylePath = join(root, 'src', 'styles', 'components.css');
const failures: string[] = [];

const [preview, styleEntry, tokenStyle, brandFontStyle, expressiveFontStyle, localeFontStyle, componentStyle] = await Promise.all([
  readFile(previewPath, 'utf8'),
  readFile(styleEntryPath, 'utf8'),
  readFile(tokenStylePath, 'utf8'),
  readFile(brandFontStylePath, 'utf8'),
  readFile(expressiveFontStylePath, 'utf8'),
  readFile(localeFontStylePath, 'utf8'),
  readFile(componentStylePath, 'utf8')
]);

for (const importPath of ['./tokens.css', './components.css']) {
  if (!styleEntry.includes(`@import "${importPath}";`)) {
    failures.push(`Missing style entry import ${importPath}.`);
  }
}

for (const requiredText of [
  '../src/styles/index.css',
  '../src/styles/brand-fonts.css',
  '../src/styles/expressive-fonts.css',
  'zdp-brand-lockup',
  'zdp-brand-lockup__mark',
  'zdp-brand-wordmark',
  '8ailors',
  'font-family: var(--zdp-font-family-brand)',
  'font-weight: var(--zdp-font-weight-semibold)',
  '표현용 폰트',
  'type-specimen--script',
  '.type-specimen--script strong',
  'font-weight: var(--zdp-font-weight-bold)',
  'type-specimen--inscription',
  'type-specimen--sketch',
  'type-specimen--editorial',
  'type-specimen--sans',
  'type-specimen--keyboard',
  'data-zdp-theme="light"',
  'data-zdp-theme="dark"',
  'Pretendard-first multiscript text',
  'lang="zh"',
  'lang="hi"',
  'lang="ja"',
  'zdp-button zdp-button--primary zdp-button--md',
  'zdp-icon-button zdp-icon-button--solid zdp-icon-button--md',
  'zdp-icon zdp-icon--md zdp-icon-button__glyph',
  'zdp-theme-toggle zdp-theme-toggle--md',
  'data-zdp-theme-toggle',
  'data-zdp-theme-state="light"',
  'data-zdp-theme-state="dark"',
  'aria-label="다크 모드로 전환"',
  'aria-label="라이트 모드로 전환"',
  'aria-pressed="false"',
  'aria-pressed="true"',
  'zdp-theme-toggle__icon--sun',
  'zdp-theme-toggle__icon--moon',
  'zdp-inline zdp-inline--gap-sm',
  'zdp-badge zdp-badge--primary zdp-badge--md',
  'zdp-badge zdp-badge--success zdp-badge--md',
  'zdp-badge zdp-badge--warning zdp-badge--md',
  'zdp-badge zdp-badge--danger zdp-badge--md',
  'zdp-command-field-shell',
  'zdp-command-field zdp-command-field--md',
  'zdp-command-field__label',
  'zdp-command-field__input',
  'zdp-command-field__shortcut',
  'zdp-avatar zdp-avatar--sm zdp-avatar--neutral',
  'zdp-avatar zdp-avatar--md zdp-avatar--primary',
  'zdp-avatar__initials',
  'zdp-identity-chip zdp-identity-chip--md zdp-identity-chip--link',
  'zdp-identity-chip__body',
  'zdp-identity-chip__label',
  'zdp-identity-chip__description',
  'zdp-link',
  'zdp-skip-link',
  'zdp-visually-hidden',
  'zdp-page zdp-page--canvas zdp-surface-reset',
  'zdp-section zdp-section--spacing-lg zdp-section--panel',
  'zdp-container zdp-container--lg zdp-container--padding-lg',
  'zdp-page-header zdp-page-header--align-center',
  'zdp-page-header__body',
  'zdp-page-header__title',
  'zdp-page-header__summary',
  'zdp-page-header__actions',
  'zdp-stack zdp-stack--gap-md',
  'zdp-grid zdp-grid--columns-two zdp-grid--gap-md',
  'zdp-toolbar zdp-toolbar--gap-md zdp-toolbar--align-center',
  'zdp-toolbar__main',
  'zdp-toolbar__actions',
  'zdp-shortcut-hint',
  'zdp-shortcut-hint__separator',
  'zdp-kbd zdp-kbd--md',
  'zdp-inline-code',
  'zdp-code-block',
  'zdp-code-block__header',
  'zdp-code-block__meta',
  'zdp-code-block__title',
  'zdp-code-block__language',
  'zdp-code-block__copy',
  'zdp-code-block__scroller',
  'role="region" aria-label="릴리스 기준 ts 코드" tabindex="0"',
  'role="region" aria-label="보안 경계 ts 코드" tabindex="0"',
  'zdp-code-block__pre',
  'zdp-code-block__code',
  'data-wrap="true"',
  '릴리스 기준',
  '보안 경계',
  'zdp-disclosure',
  'zdp-disclosure__heading',
  'zdp-disclosure__trigger',
  'zdp-disclosure__title',
  'zdp-disclosure__mark',
  'zdp-disclosure__panel',
  'role="group"',
  'zdp-accordion',
  'zdp-accordion__item',
  'zdp-segmented-control zdp-segmented-control--md',
  'zdp-segmented-control__item',
  'zdp-segmented-control__item--selected',
  'zdp-divider zdp-divider--horizontal zdp-divider--subtle',
  'zdp-table-wrap',
  'zdp-table zdp-table--density-compact',
  'zdp-table__caption',
  'zdp-table-toolbar',
  'class="zdp-table-toolbar" role="group"',
  'zdp-table-toolbar__body',
  'zdp-table-toolbar__controls',
  'zdp-table-toolbar__actions',
  'zdp-table-toolbar__density',
  'zdp-sort-header zdp-sort-header--ascending',
  'zdp-sort-header zdp-sort-header--descending',
  'zdp-sort-header__label',
  'zdp-sort-header__mark',
  '<span class="zdp-sort-header__mark" aria-hidden="true"></span>',
  'data-sort-direction="ascending"',
  'aria-sort="ascending"',
  'aria-sort="descending"',
  '2개 선택됨',
  '표 밀도',
  'scope="col"',
  'scope="row"',
  'zdp-key-value zdp-key-value--columns-two',
  'zdp-empty-state',
  'zdp-empty-state__body',
  'zdp-empty-state__actions',
  'zdp-share-dock zdp-share-dock--inline',
  'zdp-share-dock__list',
  'zdp-share-action',
  'zdp-share-action__mark',
  'zdp-share-action__tooltip',
  'zdp-popover zdp-popover--bottom zdp-popover--align-start',
  'zdp-popover__trigger',
  'zdp-popover__panel',
  'zdp-menu zdp-menu--bottom zdp-menu--align-end',
  'zdp-menu__trigger',
  'zdp-menu__panel',
  'zdp-menu__item',
  'zdp-menu__item--danger',
  'zdp-menu__separator',
  '<span class="zdp-menu__trigger-mark" aria-hidden="true"></span>',
  'zdp-toast zdp-toast--success',
  'zdp-toast zdp-toast--warning',
  'zdp-toast zdp-toast--danger',
  'zdp-toast__mark',
  'zdp-toast__body',
  'zdp-toast__title',
  'zdp-toast__message',
  'zdp-toast__action',
  'zdp-toast__close',
  'zdp-status-toast zdp-status-toast--inline',
  'zdp-progress zdp-progress--primary zdp-progress--md',
  'zdp-progress zdp-progress--warning zdp-progress--md',
  'zdp-progress__track',
  'zdp-progress__bar',
  'zdp-spinner zdp-spinner--primary zdp-spinner--sm',
  'zdp-spinner zdp-spinner--warning zdp-spinner--md',
  'zdp-spinner__mark',
  'zdp-skeleton zdp-skeleton--text',
  'zdp-skeleton zdp-skeleton--block',
  'zdp-skeleton zdp-skeleton--avatar',
  'zdp-skeleton__line',
  'zdp-share-icon zdp-share-icon--copy',
  'zdp-share-icon zdp-share-icon--device',
  'zdp-share-icon zdp-share-icon--telegram',
  'zdp-share-icon zdp-share-icon--line',
  'zdp-share-icon zdp-share-icon--whatsapp',
  'zdp-share-icon zdp-share-icon--x',
  'zdp-share-icon zdp-share-icon--reddit',
  'zdp-callout zdp-callout--info',
  'zdp-callout zdp-callout--danger',
  'zdp-callout__mark',
  'zdp-callout__body',
  'zdp-breadcrumb',
  'zdp-breadcrumb__list',
  'zdp-breadcrumb__item',
  'zdp-breadcrumb__link',
  'zdp-breadcrumb__separator',
  'zdp-breadcrumb__current',
  'aria-current="page"',
  'zdp-pagination',
  'zdp-pagination__list',
  'zdp-pagination__item',
  'zdp-pagination__link',
  'zdp-pagination__link--control',
  'zdp-pagination__ellipsis',
  'light-pagination-title',
  'dark-pagination-title',
  '현재 5페이지',
  '현재 9페이지',
  '이전',
  '다음',
  'zdp-tabs',
  'zdp-tabs__list',
  'zdp-tabs__tab zdp-tabs__tab--active',
  'zdp-tabs__panel',
  'role="tablist"',
  'tabindex="-1"',
  'role="tabpanel"',
  'zdp-term-trigger',
  'data-term-id="operational-resilience"',
  'aria-haspopup="dialog"',
  'aria-controls="light-term-sheet"',
  'zdp-term-sheet__backdrop',
  'zdp-term-sheet zdp-term-sheet--right',
  'data-zdp-ad-exclude="true"',
  'light-term-sheet-title',
  'light-term-sheet-description',
  'zdp-term-sheet__header',
  'zdp-term-sheet__eyebrow',
  'zdp-term-sheet__title',
  'zdp-term-sheet__close',
  'zdp-term-sheet__body',
  'zdp-term-sheet__short',
  'zdp-term-sheet__section',
  'zdp-term-sheet__related',
  'zdp-term-sheet__related-button',
  'zdp-term-sheet__footer',
  'zdp-term-sheet__detail-link',
  '운영 복원력',
  '관련 용어',
  'zdp-dialog',
  'zdp-dialog__backdrop',
  'zdp-dialog__panel zdp-dialog__panel--md',
  'role="dialog"',
  'aria-modal="true"',
  'zdp-dialog__header',
  'zdp-dialog__title',
  'zdp-dialog__body',
  'zdp-dialog__footer',
  'zdp-dialog__close',
  'light-sheet-title',
  'dark-sheet-title',
  'zdp-sheet-layer',
  'zdp-sheet__backdrop',
  'zdp-sheet zdp-sheet--right zdp-sheet--md',
  'zdp-sheet zdp-sheet--bottom zdp-sheet--lg',
  'data-zdp-sheet-placement="right"',
  'data-zdp-sheet-placement="bottom"',
  'data-zdp-sheet-size="md"',
  'data-zdp-sheet-size="lg"',
  'data-zdp-sheet-surface="sheet"',
  'zdp-sheet__header',
  'zdp-sheet__title',
  'zdp-sheet__close',
  'zdp-sheet__body',
  'zdp-sheet__footer',
  'zdp-choice zdp-choice--checkbox',
  'zdp-choice zdp-choice--radio',
  'zdp-switch',
  'zdp-choice__input',
  'zdp-choice__mark',
  'zdp-switch__track',
  'zdp-field zdp-field--md',
  'zdp-label',
  'zdp-input',
  'zdp-select',
  'zdp-textarea',
  'zdp-help-text',
  'zdp-error-text',
  'zdp-surface zdp-surface--panel zdp-surface--padding-lg',
  '--zdp-color-accent-primary',
  '--zdp-color-accent-success',
  '--zdp-color-accent-warning',
  '--zdp-color-accent-danger',
  '--zdp-type-body-size',
  '--zdp-type-body-small-size',
  '--zdp-type-page-title-size',
  '--zdp-type-page-title-compact-size',
  '--zdp-type-page-title-line-height',
  '--zdp-type-caption-size',
  '--zdp-type-data-size',
  '--zdp-breakpoint-tablet',
  '--zdp-control-height-md',
  '--zdp-control-border-width',
  '--zdp-control-choice-size',
  '--zdp-control-switch-width',
  '--zdp-control-scrollbar-size',
  '--zdp-control-focus-outline-width',
  '--zdp-i18n-overflow-wrap',
  'line-height: var(--zdp-type-title-line-height)',
  'font-size: calc(var(--zdp-type-page-title-size) - 0.8rem)',
  'font-size: calc(var(--zdp-type-page-title-compact-size) - 0.5rem)',
  'line-height: var(--zdp-type-page-title-line-height)',
  'Foundation tokens',
  'Search Design System',
  'light-command-title',
  'dark-command-title',
  'light-combobox-title',
  'dark-combobox-title',
  '프로젝트, 문서, 설정 검색',
  'light-command-help',
  'dark-command-help',
  '이 화면에서 찾을 항목을 입력하세요.',
  '필요한 항목으로 바로 이동하세요.',
  'zdp-combobox zdp-combobox--md',
  'zdp-combobox__control',
  'zdp-combobox__input',
  'role="combobox"',
  'aria-autocomplete="list"',
  'aria-haspopup="listbox"',
  'aria-activedescendant="light-owner-option-platform"',
  'aria-activedescendant="dark-owner-option-security"',
  'zdp-combobox__toggle',
  'zdp-combobox__mark',
  'zdp-combobox__panel',
  'zdp-combobox__listbox',
  'role="listbox" aria-label="담당 목록"',
  'zdp-combobox__option',
  'zdp-combobox__option-label',
  'zdp-combobox__option-description',
  '가장 가까운 담당 팀을 선택하세요.',
  'Light shortcut hints',
  'Dark shortcut hints',
  'role="group" aria-label="Light shortcut hints"',
  'role="group" aria-label="Dark shortcut hints"',
  'role="group" aria-label="Search shortcut slash"',
  'role="group" aria-label="Shortcut guide question mark"',
  'role="group" aria-label="Submit shortcut Mod Enter"',
  'Search shortcut slash',
  'Shortcut guide question mark',
  'Close shortcut Escape',
  'Open shortcut Enter',
  'Previous shortcut ArrowUp',
  'Next shortcut ArrowDown',
  'Ctrl/⌘',
  '화면의 첫 장면',
  '반복되는 요약',
  '검토 흐름',
  '출시 노트 보기',
  '업데이트 보기',
  '자세히 보기',
  'light-forms-title',
  'dark-forms-title',
  '공개 표기와 알림에 사용됩니다.',
  '이미 발급된 값은 그대로 둡니다.',
  'readonly',
  '다음 단계 전에 기준을 확인하세요.',
  '업데이트 받기',
  '알림 주기',
  '자동 저장',
  '작성 중인 내용을 임시 보관합니다.',
  'light-feedback-title',
  'dark-feedback-title',
  'light-identity-title',
  'dark-identity-title',
  'light-data-title',
  'dark-data-title',
  '보안 점검 목록',
  '원장 경계',
  '아직 공개할 변경이 없습니다.',
  '대기 중인 알림이 없습니다.',
  'light-breadcrumb-title',
  'dark-breadcrumb-title',
  'light-tabs-title',
  'dark-tabs-title',
  'light-dialog-title',
  'dark-dialog-title',
  'light-popover-title',
  'dark-popover-title',
  'light-disclosure-title',
  'dark-disclosure-title',
  'light-segmented-control-title',
  'dark-segmented-control-title',
  'role="group"',
  'aria-labelledby="light-disclosure-trigger"',
  'aria-labelledby="dark-disclosure-trigger"',
  'aria-label="밝은 화면 접힌 안내"',
  'aria-label="어두운 화면 접힌 안내"',
  'role="radiogroup"',
  'role="radio"',
  'aria-checked="true"',
  'aria-checked="false"',
  '밝은 화면 보기 방식',
  '어두운 화면 보기 방식',
  'role="menu" aria-labelledby="light-menu-trigger"',
  'role="menu" aria-labelledby="dark-menu-trigger"',
  'aria-haspopup="menu"',
  'aria-expanded="true"',
  '필터',
  '더보기',
  '필터 저장',
  '연결 끊기',
  '검토 기준',
  '필요한 기준만 펼쳐서 확인합니다.',
  '접힌 안내',
  '보기 방식',
  '목록',
  '카드',
  '요약',
  'Identity',
  '홍길동',
  '김하늘',
  '검토 담당',
  '운영 담당',
  '저장됐습니다.',
  '초안이 준비됐습니다.',
  '확인이 필요합니다.',
  '연결이 끊겼습니다.',
  '기록 보기',
  '다시 연결',
  '자료를 불러오는 중입니다.',
  '목록 확인 중',
  '응답을 기다리고 있습니다.',
  '응답 대기 중',
  'aria-valuenow="72"',
  'data-indeterminate="true"',
  'aria-live="polite"',
  'aria-atomic="true"',
  '검토 중',
  '정상',
  '삭제 전에 다시 확인하세요.',
  '작업 흐름이 준비됐습니다.',
  '위험 작업 전에 다시 확인하세요.',
  '탭은 페이지 안의 가까운 정보 묶음을 바꿀 때 사용합니다.'
]) {
  if (!preview.includes(requiredText)) {
    failures.push(`Preview is missing ${requiredText}.`);
  }
}

for (const forbiddenText of [
  'preview-stage" aria-label=',
  '<section class="preview-section" aria-labelledby=',
  '<section class="motif-strip"',
  'motif-strip" aria-label=',
  'aria-label="Status badges"',
  '<span class="motif-strip__mark" aria-hidden="true">✦</span>'
]) {
  if (preview.includes(forbiddenText)) {
    failures.push(`Preview must not expose decorative preview structure through ${forbiddenText}.`);
  }
}

if (!preview.includes('<div class="motif-strip" aria-hidden="true">')) {
  failures.push('Preview decorative motif must be hidden from assistive technology.');
}

if (!preview.includes('<span class="motif-strip__mark" aria-hidden="true"></span>')) {
  failures.push('Preview decorative motif mark must be hidden from assistive technology.');
}

for (const [iconName, expectedPath] of [
  ['telegram', siTelegram.path],
  ['line', siLine.path],
  ['whatsapp', siWhatsapp.path],
  ['x', siX.path],
  ['reddit', siReddit.path]
] as const) {
  if (!preview.includes(`zdp-share-icon zdp-share-icon--${iconName}`)) {
    failures.push(`Preview is missing ${iconName} share icon class.`);
  }

  if (!preview.includes(`d="${expectedPath}" fill="currentColor"`)) {
    failures.push(`Preview ${iconName} icon must match the Simple Icons path.`);
  }
}

for (const requiredText of [
  '.zdp-surface-reset a:not(.zdp-button):not(.zdp-icon-button):not(.zdp-share-action)',
  'font-family: var(--zdp-font-family-sans)',
  'Pretendard Variable',
  '--zdp-font-family-latin',
  '--zdp-font-family-korean',
  '--zdp-font-family-chinese',
  '--zdp-font-family-devanagari',
  '--zdp-font-family-brand',
  '--zdp-font-family-expression-script',
  '--zdp-font-family-expression-inscription',
  '--zdp-font-family-expression-sketch',
  '--zdp-font-family-expression-editorial',
  '--zdp-font-family-expression-sans',
  '--zdp-font-family-expression-keyboard',
  '.zdp-surface-reset:lang(ko)',
  '.zdp-surface-reset:lang(zh)',
  '.zdp-surface-reset:lang(hi)',
  '.zdp-surface-reset:lang(ja)',
  'text-decoration-line: none',
  'color var(--zdp-motion-fast) ease',
  '--zdp-color-focus-surface',
  '--zdp-color-focus-text',
  '--zdp-color-focus-line',
  '--zdp-color-scrollbar-track',
  '--zdp-color-scrollbar-thumb',
  '--zdp-color-scrollbar-thumb-hover',
  '--zdp-color-selection-surface',
  '--zdp-color-selection-text',
  '--zdp-control-scrollbar-size',
  'scrollbar-width: thin',
  '::-webkit-scrollbar-thumb',
  '.zdp-surface-reset::selection',
  '.zdp-surface-reset *::selection',
  'background: var(--zdp-color-selection-surface)',
  'color: var(--zdp-color-selection-text)',
  'border-bottom: var(--zdp-control-focus-underline-width) solid var(--zdp-color-focus-line)',
  '.zdp-surface-reset :where(input, textarea, select):focus-visible',
  'outline: var(--zdp-control-focus-outline-width) solid var(--zdp-color-focus-surface)',
  '--zdp-type-body-line-height: 1.6',
  '--zdp-font-line-height-normal: 1.6'
]) {
  if (!tokenStyle.includes(requiredText)) {
    failures.push(`Token style contract is missing ${requiredText}.`);
  }
}

for (const requiredText of [
  'font-family: "Playwrite AU VIC Guides"',
  'font-display: swap',
  'fontsource/fonts/playwrite-au-vic-guides@5.2.6/latin-400-normal.woff2'
]) {
  if (!brandFontStyle.includes(requiredText)) {
    failures.push(`Brand font style contract is missing ${requiredText}.`);
  }
}

for (const requiredText of [
  'family=Cabin:ital,wght@0,400..700;1,400..700',
  'family=Caesar+Dressing',
  'family=Copse',
  'family=Fredericka+the+Great',
  'family=Google+Sans',
  'family=Libertinus+Keyboard',
  'family=Merriweather:ital,wght@0,400;0,700;1,400',
  'family=Tangerine:wght@400;700'
]) {
  if (!expressiveFontStyle.includes(requiredText)) {
    failures.push(`Expressive font style contract is missing ${requiredText}.`);
  }
}

for (const requiredText of [
  '@fontsource-variable/manrope@5.2.8/index.css',
  '@fontsource-variable/noto-sans-sc@5.2.10/index.css',
  '@fontsource-variable/noto-sans-devanagari@5.2.8/index.css'
]) {
  if (!localeFontStyle.includes(requiredText)) {
    failures.push(`Locale font style contract is missing ${requiredText}.`);
  }
}

for (const requiredText of [
  '.zdp-user-select-control',
  '.zdp-user-select-decorative',
  '.zdp-user-select-dragging',
  '-webkit-user-select: none',
  'user-select: none',
  'font-family: var(--zdp-font-family-sans)',
  'font-weight: var(--zdp-font-weight-medium)',
  'border: var(--zdp-control-border-width) solid var(--zdp-color-line-strong)',
  'border-color: var(--zdp-color-line-subtle)',
  '.zdp-confirm-action',
  '.zdp-confirm-action__fill',
  '.zdp-confirm-action__thumb',
  '.zdp-confirm-action__glyph',
  '.zdp-confirm-action__label',
  '.zdp-confirm-action__hint',
  '.zdp-confirm-action--danger',
  '--zdp-confirm-action-progress: 0',
  'width: calc(var(--zdp-confirm-action-progress) * 100%)',
  'touch-action: none',
  'background: var(--zdp-color-accent-primary)',
  'background: var(--zdp-color-accent-danger)',
  'opacity: 0.24',
  '.zdp-button--primary:hover:not(:disabled)',
  '.zdp-button--secondary:hover:not(:disabled)',
  '.zdp-button--danger:hover:not(:disabled)',
  'background: var(--zdp-color-surface-raised)',
  '.zdp-button--primary:active:not(:disabled)',
  '.zdp-icon-button--solid:hover:not(:disabled)',
  '.zdp-icon-button--ghost:hover:not(:disabled)',
  '.zdp-icon-button--solid:active:not(:disabled)',
  '.zdp-badge',
  '.zdp-badge--primary',
  'color: var(--zdp-color-ink-strong)',
  '.zdp-badge--success',
  '.zdp-badge--warning',
  '.zdp-badge--danger',
  '.zdp-avatar',
  '.zdp-avatar--sm',
  '.zdp-avatar--md',
  '.zdp-avatar--lg',
  '.zdp-avatar--primary',
  '.zdp-avatar__image',
  '.zdp-avatar__initials',
  '.zdp-identity-chip',
  '.zdp-identity-chip--sm',
  '.zdp-identity-chip--md',
  '.zdp-identity-chip--link',
  '.zdp-identity-chip--link:hover',
  '.zdp-identity-chip--link:focus-visible',
  '.zdp-identity-chip[data-selected="true"]',
  '.zdp-identity-chip[aria-current]',
  '.zdp-identity-chip__body',
  '.zdp-identity-chip__label',
  '.zdp-identity-chip__description',
  '.zdp-link',
  '.zdp-link:hover',
  '.zdp-link:focus-visible',
  '.zdp-link[aria-current]',
  '.zdp-link--muted',
  '.zdp-skip-link',
  '.zdp-skip-link:focus-visible',
  '.zdp-visually-hidden',
  '.zdp-brand-lockup',
  '.zdp-brand-lockup__mark',
  '.zdp-brand-wordmark',
  '.zdp-surface-reset .zdp-brand-wordmark',
  'font-family: var(--zdp-font-family-brand)',
  'font-weight: var(--zdp-font-weight-semibold)',
  '.zdp-page',
  '.zdp-page--canvas',
  '.zdp-container',
  '.zdp-container--lg',
  '.zdp-container--padding-lg',
  '.zdp-section',
  '.zdp-section--spacing-lg',
  '.zdp-section--panel',
  '.zdp-page-header',
  '.zdp-page-header__body',
  '.zdp-page-header__title',
  '.zdp-page-header__summary',
  '.zdp-page-header__actions',
  '.zdp-stack',
  '.zdp-stack--gap-md',
  '.zdp-stack--align-start',
  '.zdp-inline',
  '.zdp-inline--gap-sm',
  '.zdp-inline--align-center',
  '.zdp-grid',
  '.zdp-grid--columns-two',
  '.zdp-grid--columns-auto',
  '.zdp-grid--gap-md',
  '.zdp-toolbar',
  '.zdp-toolbar__main',
  '.zdp-toolbar__actions',
  '.zdp-kbd',
  '.zdp-kbd__sr-label',
  '.zdp-kbd--sm',
  '.zdp-kbd--md',
  '.zdp-shortcut-hint',
  '.zdp-shortcut-hint--sm',
  '.zdp-shortcut-hint--md',
  '.zdp-shortcut-hint__separator',
  '.zdp-command-field-shell',
  '.zdp-command-field-shell--sm',
  '.zdp-command-field-shell--md',
  '.zdp-command-field__label',
  '.zdp-command-field__label--hidden',
  '.zdp-command-field',
  '.zdp-command-field--sm',
  '.zdp-command-field--md',
  '.zdp-command-field:hover',
  '.zdp-command-field:focus-within',
  '.zdp-command-field-shell[data-invalid="true"] .zdp-command-field',
  '.zdp-command-field-shell[data-disabled="true"] .zdp-command-field',
  '.zdp-command-field__input',
  '.zdp-command-field--sm .zdp-command-field__input',
  '.zdp-command-field__input::placeholder',
  '.zdp-command-field__input:focus',
  '.zdp-command-field__shortcut',
  '.zdp-combobox',
  '.zdp-combobox__label',
  '.zdp-combobox__control',
  '.zdp-combobox__control:focus-within',
  '.zdp-combobox__input',
  '.zdp-combobox__toggle',
  '.zdp-combobox__mark',
  '.zdp-combobox__panel',
  '.zdp-combobox__listbox',
  '.zdp-combobox__option',
  '.zdp-combobox__option[data-active="true"]',
  '.zdp-combobox__option[data-selected="true"]',
  '.zdp-combobox__option-description',
  '.zdp-combobox__empty',
  '.zdp-theme-toggle',
  '.zdp-theme-toggle--sm',
  '.zdp-theme-toggle--md',
  '.zdp-theme-toggle:hover:not(:disabled)',
  '.zdp-theme-toggle:focus-visible',
  '.zdp-theme-toggle__icon',
  '.zdp-theme-toggle__icon--moon svg',
  '.zdp-theme-toggle[data-zdp-theme-state="light"] .zdp-theme-toggle__icon--moon',
  '.zdp-theme-toggle[data-zdp-theme-state="dark"]',
  '.zdp-tooltip',
  '.zdp-tooltip__trigger',
  '.zdp-tooltip__content',
  '.zdp-tooltip--top .zdp-tooltip__content',
  '.zdp-tooltip--right .zdp-tooltip__content',
  '.zdp-tooltip--bottom .zdp-tooltip__content',
  '.zdp-tooltip--left .zdp-tooltip__content',
  '.zdp-tooltip:hover .zdp-tooltip__content',
  '.zdp-tooltip:focus-within .zdp-tooltip__content',
  '.zdp-disclosure',
  '.zdp-disclosure__heading',
  '.zdp-disclosure__trigger',
  '.zdp-disclosure__trigger:hover:not(:disabled)',
  '.zdp-disclosure__trigger:focus-visible',
  '.zdp-disclosure__trigger:disabled',
  '.zdp-disclosure__title',
  '.zdp-disclosure__mark',
  '.zdp-disclosure__panel',
  '.zdp-accordion',
  '.zdp-accordion__item',
  '.zdp-segmented-control',
  '.zdp-segmented-control__item',
  '.zdp-segmented-control--sm .zdp-segmented-control__item',
  '.zdp-segmented-control--md .zdp-segmented-control__item',
  '.zdp-segmented-control__item:hover:not(:disabled):not([aria-checked="true"])',
  '.zdp-segmented-control__item:focus-visible',
  '.zdp-segmented-control__item--selected',
  '.zdp-segmented-control__item[aria-checked="true"]',
  '.zdp-segmented-control__item:disabled',
  '.zdp-popover',
  '.zdp-popover__trigger',
  '.zdp-popover__panel',
  '.zdp-popover__panel:focus-visible',
  '.zdp-popover--bottom .zdp-popover__panel',
  '.zdp-popover--align-start .zdp-popover__panel',
  '.zdp-menu',
  '.zdp-menu__trigger',
  '.zdp-menu__trigger:focus-visible',
  '.zdp-menu__panel',
  '.zdp-menu__panel:focus-visible',
  '.zdp-menu__item',
  '.zdp-menu__item:hover:not(:disabled):not([aria-disabled="true"])',
  '.zdp-menu__item--danger',
  '.zdp-menu__separator',
  '.zdp-menu__trigger-mark::before',
  '.zdp-menu--bottom .zdp-menu__panel',
  '.zdp-menu--align-end .zdp-menu__panel',
  '.zdp-toast',
  '.zdp-toast__mark',
  '.zdp-toast__body',
  '.zdp-toast__title',
  '.zdp-toast__message',
  '.zdp-toast__action',
  '.zdp-toast__action {\n  align-items: center;',
  'margin-block-start: var(--zdp-space-3)',
  '.zdp-toast__action:focus-visible',
  '.zdp-toast__close',
  '.zdp-toast__close:focus-visible',
  '.zdp-toast--success .zdp-toast__mark',
  '.zdp-toast--warning .zdp-toast__mark',
  '.zdp-toast--danger .zdp-toast__mark',
  '.zdp-status-toast',
  '.zdp-status-toast .zdp-toast',
  '.zdp-status-toast--inline',
  '.zdp-status-toast--top-end',
  '.zdp-status-toast--bottom-end',
  '.zdp-progress',
  '.zdp-progress__track',
  '.zdp-progress__bar',
  '.zdp-progress[data-indeterminate="true"] .zdp-progress__bar',
  '.zdp-progress--success',
  '.zdp-progress--warning',
  '.zdp-progress--danger',
  '.zdp-spinner',
  '.zdp-spinner__mark',
  '.zdp-spinner--sm',
  '.zdp-spinner--md',
  '.zdp-spinner--lg',
  '.zdp-spinner--warning',
  '.zdp-skeleton',
  '.zdp-skeleton__line',
  '.zdp-skeleton--text .zdp-skeleton__line',
  '.zdp-skeleton--block .zdp-skeleton__line',
  '.zdp-skeleton--avatar .zdp-skeleton__line',
  '.zdp-skeleton[data-animated="false"] .zdp-skeleton__line',
  'prefers-reduced-motion',
  '.zdp-divider',
  '.zdp-divider--horizontal',
  '.zdp-divider--subtle',
  '.zdp-table-wrap',
  '.zdp-table',
  '.zdp-table__caption',
  '.zdp-table th',
  '.zdp-table td',
  '.zdp-inline-code',
  '.zdp-code-block',
  '--zdp-code-block-surface: var(--zdp-color-surface-panel)',
  '--zdp-code-block-surface: var(--zdp-color-surface-raised)',
  '.zdp-code-block__header',
  '.zdp-code-block__meta',
  '.zdp-code-block__title',
  '.zdp-code-block__language',
  '.zdp-code-block__copy',
  '.zdp-code-block__copy:focus-visible',
  '.zdp-code-block__scroller',
  'background: var(--zdp-code-block-surface)',
  'overscroll-behavior-inline: contain',
  '.zdp-code-block__scroller:focus-visible',
  '.zdp-code-block__pre',
  '.zdp-code-block[data-wrap="true"] .zdp-code-block__pre',
  '.zdp-sort-header',
  '.zdp-sort-header__label',
  '.zdp-sort-header__mark',
  '.zdp-sort-header__mark::before',
  '.zdp-sort-header--ascending .zdp-sort-header__mark::before',
  '.zdp-sort-header--descending .zdp-sort-header__mark::before',
  '.zdp-sort-header--ascending .zdp-sort-header__mark',
  '.zdp-table-toolbar',
  '.zdp-table-toolbar__body',
  '.zdp-table-toolbar__title',
  '.zdp-table-toolbar__summary',
  '.zdp-table-toolbar__selection',
  '.zdp-table-toolbar__controls',
  '.zdp-table-toolbar__actions',
  '.zdp-table-toolbar__density',
  '.zdp-table-toolbar__density-label',
  '.zdp-key-value',
  '.zdp-key-value dt',
  '.zdp-key-value dd',
  '.zdp-empty-state',
  '.zdp-empty-state__body',
  '.zdp-empty-state__actions',
  '.zdp-share-dock',
  '.zdp-share-dock--side',
  '.zdp-share-dock--rail',
  '.zdp-share-dock--bottom',
  '.zdp-share-dock--inline',
  '.zdp-share-dock__list',
  '.zdp-share-action',
  '.zdp-share-action:hover:not(:disabled)',
  '.zdp-share-action:focus-visible',
  '.zdp-share-action__mark',
  '.zdp-share-icon',
  '.zdp-share-action__tooltip',
  '.zdp-share-action:hover .zdp-share-action__tooltip',
  'max-inline-size: calc(100vw - var(--zdp-space-6))',
  'border-block-start: 1px solid var(--zdp-color-line-subtle)',
  'display: flex',
  'flex-wrap: wrap',
  'display: grid',
  'min-width: 0',
  'position: fixed',
  'pointer-events: none',
  'pointer-events: auto',
  'clip: rect(0 0 0 0)',
  'clip-path: inset(50%)',
  'position: absolute',
  'white-space: nowrap',
  '.zdp-callout',
  '.zdp-callout__mark',
  '.zdp-callout__body',
  'height: calc(var(--zdp-type-body-small-size) * var(--zdp-type-body-small-line-height))',
  '.zdp-callout--info .zdp-callout__mark',
  '.zdp-callout--success .zdp-callout__mark',
  '.zdp-callout--warning .zdp-callout__mark',
  '.zdp-callout--danger .zdp-callout__mark',
  '.zdp-breadcrumb',
  '.zdp-breadcrumb__list',
  '.zdp-breadcrumb__item',
  '.zdp-breadcrumb__link',
  '.zdp-breadcrumb__link:focus-visible',
  '.zdp-breadcrumb__current',
  '.zdp-breadcrumb__separator',
  '.zdp-pagination',
  '.zdp-pagination__list',
  '.zdp-pagination__item',
  '.zdp-pagination__link',
  '.zdp-pagination__link--control',
  'overflow-x: auto',
  '--zdp-pagination-focus-bleed',
  'padding-block: var(--zdp-pagination-focus-bleed)',
  'padding-inline: var(--zdp-pagination-focus-bleed)',
  'scrollbar-gutter: stable',
  'scroll-padding-inline: var(--zdp-pagination-focus-bleed)',
  'touch-action: pan-x pan-y',
  'flex-wrap: nowrap',
  'width: max-content',
  'white-space: nowrap',
  '.zdp-pagination__link:hover:not(:disabled):not([aria-current="page"])',
  '.zdp-pagination__link:focus-visible',
  '.zdp-pagination__link[aria-current="page"]',
  '.zdp-pagination__link:disabled',
  '.zdp-pagination__ellipsis',
  '.zdp-tabs',
  '.zdp-tabs__list',
  '.zdp-tabs__tab',
  '.zdp-tabs__tab--active',
  '.zdp-tabs__tab:focus-visible',
  '.zdp-tabs__panel',
  '.zdp-tabs__panel:focus-visible',
  '.zdp-term-trigger',
  '.zdp-term-trigger:hover:not(:disabled)',
  '.zdp-term-trigger:focus-visible',
  '.zdp-term-sheet__backdrop',
  '.zdp-term-sheet',
  '.zdp-term-sheet--right',
  '.zdp-term-sheet--bottom',
  '.zdp-term-sheet:focus-visible',
  '.zdp-term-sheet__header',
  '.zdp-term-sheet__heading',
  '.zdp-term-sheet__eyebrow',
  '.zdp-term-sheet__title',
  '.zdp-term-sheet__close',
  '.zdp-term-sheet__body',
  '.zdp-term-sheet__short',
  '.zdp-term-sheet__section',
  '.zdp-term-sheet__related',
  '.zdp-term-sheet__related-button',
  '.zdp-term-sheet__footer',
  '.zdp-term-sheet__detail-link',
  '.zdp-dialog',
  '.zdp-dialog__backdrop',
  '.zdp-dialog__panel',
  '.zdp-dialog__panel--sm',
  '.zdp-dialog__panel--md',
  '.zdp-dialog__panel--lg',
  '.zdp-dialog__panel:focus-visible',
  '.zdp-dialog__close:focus-visible',
  '.zdp-dialog__footer',
  '.zdp-sheet-layer',
  '.zdp-sheet__backdrop',
  '.zdp-sheet',
  '.zdp-sheet--right',
  '.zdp-sheet--left',
  '.zdp-sheet--bottom',
  '.zdp-sheet--sm',
  '.zdp-sheet--md',
  '.zdp-sheet--lg',
  '.zdp-sheet:focus-visible',
  '.zdp-sheet__header',
  '.zdp-sheet__title',
  '.zdp-sheet__body',
  '.zdp-sheet__footer',
  '.zdp-sheet__close',
  '.zdp-sheet__close:focus-visible',
  '.zdp-field',
  '.zdp-label',
  '.zdp-input',
  '.zdp-textarea',
  '.zdp-select',
  '.zdp-help-text',
  '.zdp-error-text',
  '.zdp-input:hover:not(:disabled)',
  '.zdp-textarea:hover:not(:disabled)',
  '.zdp-select:hover:not(:disabled)',
  '.zdp-input:focus-visible',
  '.zdp-textarea:focus-visible',
  '.zdp-select:focus-visible',
  '.zdp-input[aria-invalid="true"]',
  '.zdp-textarea[aria-invalid="true"]',
  '.zdp-select[aria-invalid="true"]',
  '.zdp-input[readonly]',
  '.zdp-textarea[readonly]',
  '.zdp-choice',
  '.zdp-switch',
  '.zdp-choice__input',
  '.zdp-switch__input',
  '.zdp-choice__mark',
  '.zdp-switch__track',
  'border-bottom: 2px solid currentcolor',
  'border-left: 2px solid currentcolor',
  '.zdp-choice:hover .zdp-choice__input:not(:checked):not(:disabled) + .zdp-choice__mark',
  '.zdp-switch:hover .zdp-switch__input:not(:checked):not(:disabled) + .zdp-switch__track',
  'grid-template-columns: var(--zdp-control-choice-size) minmax(0, 1fr)',
  'grid-template-columns: var(--zdp-control-switch-width) minmax(0, 1fr)',
  'height: var(--zdp-control-choice-size)',
  'height: var(--zdp-control-switch-height)',
  'width: var(--zdp-control-switch-width)',
  '.zdp-choice__input:checked + .zdp-choice__mark',
  '.zdp-switch__input:checked + .zdp-switch__track',
  '.zdp-choice__input:focus-visible + .zdp-choice__mark',
  '.zdp-switch__input:focus-visible + .zdp-switch__track',
  '.zdp-choice__input[aria-invalid="true"] + .zdp-choice__mark',
  'outline: var(--zdp-control-focus-outline-width) solid var(--zdp-color-focus-surface)',
  'border-color: var(--zdp-color-focus-line)',
  '.zdp-icon',
  '.zdp-icon--sm',
  '.zdp-icon--md',
  'font-size: var(--zdp-control-glyph-md)',
  '.zdp-icon-button__glyph',
  'align-items: center',
  'justify-content: center',
  'text-align: center',
  'line-height: 1'
]) {
  if (!componentStyle.includes(requiredText)) {
    failures.push(`Component style contract is missing ${requiredText}.`);
  }
}

for (const forbiddenText of [
  'selectstart',
  'user-select: none !important',
  'body {\n  user-select: none',
  '.zdp-page {\n  user-select: none',
  '.zdp-table td {\n  user-select: none',
  '.zdp-code-block__pre {\n  user-select: none',
  '.zdp-toast__message {\n  user-select: none'
]) {
  if (componentStyle.includes(forbiddenText) || tokenStyle.includes(forbiddenText) || preview.includes(forbiddenText)) {
    failures.push(`Text selection behavior must not include broad or JS selection blocking: ${forbiddenText}.`);
  }
}

assertNoDecorativeEffects(failures, 'Token style contract', tokenStyle);
assertNoDecorativeEffects(failures, 'Locale font style contract', localeFontStyle);
assertNoDecorativeEffects(failures, 'Component style contract', componentStyle);
assertNoDecorativeEffects(failures, 'Preview', preview);
assertNoOverRoundedUsage(failures, 'Component style contract', componentStyle);
assertNoOverRoundedUsage(failures, 'Preview', preview);

if (failures.length > 0) {
  for (const failure of failures) {
    console.error(failure);
  }

  process.exitCode = 1;
}
