import assert from 'node:assert/strict';
import { readFile, readdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const directory = resolve(root, 'src/styles/component-parts');
const output = resolve(root, 'src/styles/components.css');
const names = [
  '01-foundation.css',
  '02-layout-navigation.css',
  '03-form-controls.css',
  '04-feedback-data.css',
  '05-overlays-utilities.css'
];
const actualNames = (await readdir(directory)).filter((name) => name.endsWith('.css')).sort();
assert.deepEqual(actualNames, names, 'Register every component CSS fragment in cascade order.');
const fragments = await Promise.all(names.map(async (name) => {
  const source = (await readFile(resolve(directory, name), 'utf8')).replace(/\r\n/g, '\n');
  assert.ok(Buffer.byteLength(source) <= 40_000, `Split ${name} before it exceeds 40 KB.`);
  return source.trimEnd();
}));
const rendered = '/* Generated by scripts/generate-component-styles.ts; edit component-parts/*.css. */\n'
  + fragments.join('\n\n') + '\n';
const current = (await readFile(output, 'utf8')).replace(/\r\n/g, '\n');
if (process.argv.includes('--check')) {
  assert.ok(current === rendered, 'Shared component CSS is stale; run the configured generation intent.');
} else if (current !== rendered) {
  await writeFile(output, rendered);
}
console.log(`Component CSS ${process.argv.includes('--check') ? 'check' : 'generation'} passed for ${names.length} fragments.`);
